#!/usr/bin/python

"""KernelTLV Linux Hacking Utility

Usage:
    khack-module make
    khack-module clean
    khack-module install
"""

import codecs
import sys

from docopt import docopt
from subprocess import call

UTF8Writer = codecs.getwriter('utf8')
sys.stdout = UTF8Writer(sys.stdout)

home_dir = '/home/vagrant'
linux_source = '/home/vagrant/linux-source'
libc_source = '/home/vagrant/glibc-source'

args = docopt(__doc__)
if args['make']:
    call('make M=../module -C {} -j8'.format(linux_source), shell=True)
elif args['clean']:
    call('make M=../module -C {} clean'.format(linux_source), shell=True)
elif args['install']:
    pass