#!/usr/bin/python

"""KernelTLV Linux Hacking Utility

Usage:
    khack-libc get
"""

import codecs
import sys

from docopt import docopt
from subprocess import call

UTF8Writer = codecs.getwriter('utf8')
sys.stdout = UTF8Writer(sys.stdout)

home_dir = '/home/vagrant'
linux_source = '/home/vagrant/linux-source'
libc_source = '/home/vagrant/glibc-source'

args = docopt(__doc__)
if args['get']:
    call('sudo apt-get install -y gawk glibc-source && mkdir -p {} && tar -x -f /usr/src/glibc/glibc-* --strip 1 -C {}'.format(libc_source, libc_source), shell=True)